# Site settings
title: Suryatej Reddy
email: svyalla3[at]gatech[dot]edu
description: > # this means to ignore newlines until "baseurl:"
  Graduate student in Computer Science at Georgia Institute of Technology. Interested in Systems + ML. Past work @ Adobe, MIT, IIITD, TCS Research.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://suryatereddy.github.io/" # the base hostname & protocol for your site
production_url: "https://suryatereddy.github.io/"
github_username: suryatejreddy
permalink: /blog/:year/:month/:title.html


twitter:
  username: ReddySuryatej

sass:
  style: compressed

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
