# Site settings
title: Suryatej Reddy
email: suryatej16102[at]iiitd[dot]ac[dot]in
description: > # this means to ignore newlines until "baseurl:"
  Research Assistant at MIT. Incoming MTS at Adobe. I am passionate about building tools and technologies around research ideas. B.Tech in Computer Science from IIITD.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://suryatereddy.github.io/" # the base hostname & protocol for your site
production_url: "https://suryatereddy.github.io/"
github_username: suryatejreddy
permalink: /blog/:year/:month/:title.html


twitter:
  username: ReddySuryatej

sass:
  style: compressed

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
